export const UPDATE_WAITING_BOOKMARKS = 'UPDATE_WAITING_BOOKMARKS';
export const UPDATE_BLOCKED_BOOKMARKS = 'UPDATE_BLOCKED_BOOKMARKS';

export const ADD_BLOCKED_BOOKMARK = 'ADD_BLOCKED_BOOKMARK';
export const ADD_WAITING_BOOKMARK = 'ADD_WAITING_BOOKMARK';

export const UPDATE_CONFIG = 'UPDATE_CONFIG';
export const UPDATE_STATUS = 'UPDATE_STATUS';
export const UPDATE_RANDOM = 'UPDATE_RANDOM';
export const UPDATE_FREQUENCY = 'UPDATE_FREQUENCY';
export const UPDATE_FREQUENCY_COUNTER = 'UPDATE_FREQUENCY_COUNTER';

export const UPDATE_CURRENT_NOTIFY_POSITION = 'UPDATE_CURRENT_NOTIFY_POSITION';
